plugin.tx_clubmanager.settings.contentBlockerMode: 'cookieman'
plugin.tx_cookieman.settings.theme: 'bootstrap5-modal'
clubmanagerCookieman.links.dataProtectionDeclarationPid: 0
clubmanagerCookieman.links.imprintPid: 0
