services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Quicko\Clubmanager\:
    resource: "../Classes/*"

  Quicko\Clubmanager\Utils\UniversalTypoScriptService:
    public: true

  Quicko\Clubmanager\Utils\ForgotPasswordHashGenerator:
    public: true

  Quicko\Clubmanager\Updates\MemberStatusHistoryUpgradeWizard:
    tags:
      - name: install.upgradewizard
        identifier: clubmanagerMemberStatusHistory
